///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c73fdcd6-23bd-470d-b0b4-8e2c80e498d3")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.AUDIPrelabelTool1821222AppFolder _audiprelabeltool1821222;
        MyTest1RepositoryFolders.Qt5QWindowIconAppFolder _qt5qwindowicon;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("c73fdcd6-23bd-470d-b0b4-8e2c80e498d3")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "c73fdcd6-23bd-470d-b0b4-8e2c80e498d3", ".\\RepositoryImages\\MyTest1Repositoryc73fdcd6.rximgres")
        {
            _audiprelabeltool1821222 = new MyTest1RepositoryFolders.AUDIPrelabelTool1821222AppFolder(this);
            _qt5qwindowicon = new MyTest1RepositoryFolders.Qt5QWindowIconAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c73fdcd6-23bd-470d-b0b4-8e2c80e498d3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AUDIPrelabelTool1821222 folder.
        /// </summary>
        [RepositoryFolder("0ff33e2d-609f-420d-b2ab-e2acd16b1b00")]
        public virtual MyTest1RepositoryFolders.AUDIPrelabelTool1821222AppFolder AUDIPrelabelTool1821222
        {
            get { return _audiprelabeltool1821222; }
        }

        /// <summary>
        /// The Qt5QWindowIcon folder.
        /// </summary>
        [RepositoryFolder("0a60dc0e-5fee-4f61-9ba3-41dba808fff8")]
        public virtual MyTest1RepositoryFolders.Qt5QWindowIconAppFolder Qt5QWindowIcon
        {
            get { return _qt5qwindowicon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The AUDIPrelabelTool1821222AppFolder folder.
        /// </summary>
        [RepositoryFolder("0ff33e2d-609f-420d-b2ab-e2acd16b1b00")]
        public partial class AUDIPrelabelTool1821222AppFolder : RepoGenBaseFolder
        {
            MyTest1RepositoryFolders.Client5Folder _client5;
            RepoItemInfo _pushbuttonInfo;
            RepoItemInfo _pushbutton1Info;

            /// <summary>
            /// Creates a new AUDIPrelabelTool1821222  folder.
            /// </summary>
            public AUDIPrelabelTool1821222AppFolder(RepoGenBaseFolder parentFolder) :
                    base("AUDIPrelabelTool1821222", "/form[@title>'AUDI Prelabel Tool (1.8.2']", parentFolder, 30000, null, true, "0ff33e2d-609f-420d-b2ab-e2acd16b1b00", "")
            {
                _client5 = new MyTest1RepositoryFolders.Client5Folder(this);
                _pushbuttonInfo = new RepoItemInfo(this, "PushButton", "container[1]/container[2]/button[1]", "", 30000, null, "4ecca0f3-3391-4821-a0e7-3056e1ade3b3");
                _pushbutton1Info = new RepoItemInfo(this, "PushButton1", "container[1]/container[2]/button[2]", "", 30000, null, "95b2a931-a34c-4ddb-9598-33b665a1bf31");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0ff33e2d-609f-420d-b2ab-e2acd16b1b00")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0ff33e2d-609f-420d-b2ab-e2acd16b1b00")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("4ecca0f3-3391-4821-a0e7-3056e1ade3b3")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("4ecca0f3-3391-4821-a0e7-3056e1ade3b3")]
            public virtual RepoItemInfo PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }

            /// <summary>
            /// The PushButton1 item.
            /// </summary>
            [RepositoryItem("95b2a931-a34c-4ddb-9598-33b665a1bf31")]
            public virtual Ranorex.Button PushButton1
            {
                get
                {
                    return _pushbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton1 item info.
            /// </summary>
            [RepositoryItemInfo("95b2a931-a34c-4ddb-9598-33b665a1bf31")]
            public virtual RepoItemInfo PushButton1Info
            {
                get
                {
                    return _pushbutton1Info;
                }
            }

            /// <summary>
            /// The Client5 folder.
            /// </summary>
            [RepositoryFolder("a7759cd2-fe51-403e-a901-6bba4da461cb")]
            public virtual MyTest1RepositoryFolders.Client5Folder Client5
            {
                get { return _client5; }
            }
        }

        /// <summary>
        /// The Client5Folder folder.
        /// </summary>
        [RepositoryFolder("a7759cd2-fe51-403e-a901-6bba4da461cb")]
        public partial class Client5Folder : RepoGenBaseFolder
        {
            RepoItemInfo _mfk5Info;
            RepoItemInfo _client2Info;
            RepoItemInfo _clientInfo;
            RepoItemInfo _client1Info;
            RepoItemInfo _client3Info;
            RepoItemInfo _client4Info;

            /// <summary>
            /// Creates a new Client5  folder.
            /// </summary>
            public Client5Folder(RepoGenBaseFolder parentFolder) :
                    base("Client5", "container[2]", parentFolder, 30000, null, false, "a7759cd2-fe51-403e-a901-6bba4da461cb", "")
            {
                _mfk5Info = new RepoItemInfo(this, "MFK5", ".//tabpagelist[@accessiblename='MFK5']/tabpage[@accessiblename='MFK5']", "", 30000, null, "a4c16f50-7b78-4d01-9665-e9e2e0f22f4e");
                _client2Info = new RepoItemInfo(this, "Client2", "container[1]/container[@accessiblerole='Pane']/container[@accessiblerole='Client']/container[14]", "", 30000, null, "e9f28806-7b63-4243-a7f7-503f8ad0876d");
                _clientInfo = new RepoItemInfo(this, "Client", "container[1]/container[@accessiblerole='Pane']/container[@accessiblerole='Client']/container[1]", "", 30000, null, "9a1a07d6-237f-41fa-a745-bfd24a94b8fc");
                _client1Info = new RepoItemInfo(this, "Client1", "container[1]/container[@accessiblerole='Pane']/container[@accessiblerole='Client']/container[25]", "", 30000, null, "3cad857e-e6b6-4d50-88cf-930f850602cc");
                _client3Info = new RepoItemInfo(this, "Client3", "container[1]/container[@accessiblerole='Pane']/container[@accessiblerole='Client']/container[34]", "", 30000, null, "f32e7408-c49f-4183-9f85-d903c6f62a7b");
                _client4Info = new RepoItemInfo(this, "Client4", "container[1]/container[@accessiblerole='Pane']/container[@accessiblerole='Client']/container[46]", "", 30000, null, "0ac845b4-5908-4628-8a23-00eeea6a132f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7759cd2-fe51-403e-a901-6bba4da461cb")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7759cd2-fe51-403e-a901-6bba4da461cb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MFK5 item.
            /// </summary>
            [RepositoryItem("a4c16f50-7b78-4d01-9665-e9e2e0f22f4e")]
            public virtual Ranorex.TabPage MFK5
            {
                get
                {
                    return _mfk5Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MFK5 item info.
            /// </summary>
            [RepositoryItemInfo("a4c16f50-7b78-4d01-9665-e9e2e0f22f4e")]
            public virtual RepoItemInfo MFK5Info
            {
                get
                {
                    return _mfk5Info;
                }
            }

            /// <summary>
            /// The Client2 item.
            /// </summary>
            [RepositoryItem("e9f28806-7b63-4243-a7f7-503f8ad0876d")]
            public virtual Ranorex.Container Client2
            {
                get
                {
                    return _client2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client2 item info.
            /// </summary>
            [RepositoryItemInfo("e9f28806-7b63-4243-a7f7-503f8ad0876d")]
            public virtual RepoItemInfo Client2Info
            {
                get
                {
                    return _client2Info;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("9a1a07d6-237f-41fa-a745-bfd24a94b8fc")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("9a1a07d6-237f-41fa-a745-bfd24a94b8fc")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The Client1 item.
            /// </summary>
            [RepositoryItem("3cad857e-e6b6-4d50-88cf-930f850602cc")]
            public virtual Ranorex.Container Client1
            {
                get
                {
                    return _client1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client1 item info.
            /// </summary>
            [RepositoryItemInfo("3cad857e-e6b6-4d50-88cf-930f850602cc")]
            public virtual RepoItemInfo Client1Info
            {
                get
                {
                    return _client1Info;
                }
            }

            /// <summary>
            /// The Client3 item.
            /// </summary>
            [RepositoryItem("f32e7408-c49f-4183-9f85-d903c6f62a7b")]
            public virtual Ranorex.Container Client3
            {
                get
                {
                    return _client3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client3 item info.
            /// </summary>
            [RepositoryItemInfo("f32e7408-c49f-4183-9f85-d903c6f62a7b")]
            public virtual RepoItemInfo Client3Info
            {
                get
                {
                    return _client3Info;
                }
            }

            /// <summary>
            /// The Client4 item.
            /// </summary>
            [RepositoryItem("0ac845b4-5908-4628-8a23-00eeea6a132f")]
            public virtual Ranorex.Container Client4
            {
                get
                {
                    return _client4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client4 item info.
            /// </summary>
            [RepositoryItemInfo("0ac845b4-5908-4628-8a23-00eeea6a132f")]
            public virtual RepoItemInfo Client4Info
            {
                get
                {
                    return _client4Info;
                }
            }
        }

        /// <summary>
        /// The Qt5QWindowIconAppFolder folder.
        /// </summary>
        [RepositoryFolder("0a60dc0e-5fee-4f61-9ba3-41dba808fff8")]
        public partial class Qt5QWindowIconAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _noneInfo;
            RepoItemInfo _clientInfo;

            /// <summary>
            /// Creates a new Qt5QWindowIcon  folder.
            /// </summary>
            public Qt5QWindowIconAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Qt5QWindowIcon", "/form[@class='Qt5QWindowIcon']", parentFolder, 30000, null, true, "0a60dc0e-5fee-4f61-9ba3-41dba808fff8", "")
            {
                _noneInfo = new RepoItemInfo(this, "None", "?/?/picture", "", 30000, null, "cc2b7d0e-6f87-4958-965b-97276ac05153");
                _clientInfo = new RepoItemInfo(this, "Client", "container[1]", "", 30000, null, "7d357496-a15d-450e-87ea-1a179bbafee4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a60dc0e-5fee-4f61-9ba3-41dba808fff8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a60dc0e-5fee-4f61-9ba3-41dba808fff8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("cc2b7d0e-6f87-4958-965b-97276ac05153")]
            public virtual Ranorex.Picture None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("cc2b7d0e-6f87-4958-965b-97276ac05153")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("7d357496-a15d-450e-87ea-1a179bbafee4")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("7d357496-a15d-450e-87ea-1a179bbafee4")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
