///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PreLabel recording.
    /// </summary>
    [TestModule("1ac79bdd-9f68-44f1-bbca-7829a5996db9", ModuleType.Recording, 1)]
    public partial class PreLabel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static PreLabel instance = new PreLabel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PreLabel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PreLabel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.PushButton' at 74;42.", repo.AUDIPrelabelTool1821222.PushButtonInfo, new RecordItemIndex(0));
            repo.AUDIPrelabelTool1821222.PushButton.Click("74;42");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.Client' at 288;166.", repo.AUDIPrelabelTool1821222.Client5.ClientInfo, new RecordItemIndex(1));
            repo.AUDIPrelabelTool1821222.Client5.Client.Click("288;166");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.Client1' at -646;-186.", repo.AUDIPrelabelTool1821222.Client5.Client1Info, new RecordItemIndex(2));
            repo.AUDIPrelabelTool1821222.Client5.Client1.Click("-646;-186");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qt5QWindowIcon.None' at 56;60.", repo.Qt5QWindowIcon.NoneInfo, new RecordItemIndex(3));
            repo.Qt5QWindowIcon.None.Click("56;60");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qt5QWindowIcon.None' at -89;392.", repo.Qt5QWindowIcon.NoneInfo, new RecordItemIndex(4));
            repo.Qt5QWindowIcon.None.Click("-89;392");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.Client2' at 1219;325.", repo.AUDIPrelabelTool1821222.Client5.Client2Info, new RecordItemIndex(5));
            repo.AUDIPrelabelTool1821222.Client5.Client2.Click("1219;325");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AUDIPrelabelTool1821222.Client5.Client1' at 294;321.", repo.AUDIPrelabelTool1821222.Client5.Client1Info, new RecordItemIndex(6));
            repo.AUDIPrelabelTool1821222.Client5.Client1.MoveTo("294;321");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AUDIPrelabelTool1821222.Client5.Client1' at 304;318.", repo.AUDIPrelabelTool1821222.Client5.Client1Info, new RecordItemIndex(7));
            repo.AUDIPrelabelTool1821222.Client5.Client1.MoveTo("304;318");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.MFK5' at 1395;518.", repo.AUDIPrelabelTool1821222.Client5.MFK5Info, new RecordItemIndex(8));
            repo.AUDIPrelabelTool1821222.Client5.MFK5.Click("1395;518");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.Client3' at 138;144.", repo.AUDIPrelabelTool1821222.Client5.Client3Info, new RecordItemIndex(9));
            repo.AUDIPrelabelTool1821222.Client5.Client3.Click("138;144");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.PushButton1' at 94;66.", repo.AUDIPrelabelTool1821222.PushButton1Info, new RecordItemIndex(10));
            repo.AUDIPrelabelTool1821222.PushButton1.Click("94;66");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qt5QWindowIcon.Client' at 1298;814.", repo.Qt5QWindowIcon.ClientInfo, new RecordItemIndex(11));
            repo.Qt5QWindowIcon.Client.Click("1298;814");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AUDIPrelabelTool1821222.Client5.Client4' at 1902;-495.", repo.AUDIPrelabelTool1821222.Client5.Client4Info, new RecordItemIndex(12));
            repo.AUDIPrelabelTool1821222.Client5.Client4.Click("1902;-495");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
